pipeline {
    agent any

    tools {
        maven 'mvn-v3.6.0'
        jdk 'jdk8'
    }
	
	
	environment {
        DOCKER_CREDENTIALS = credentials('ECRRegistry')
    }
    
    stages {
		
	
        stage('Build') {
            steps {
                echo 'Building......'
                sh 'mvn clean package -DskipTests=True'
            }

        }
        
        stage ('Docker Build') {
            steps {
                // prepare docker build context
                sh 'pwd'
                sh 'ls -lrt'
                
                // Build and push image with Jenkins' docker-plugin
                script {
                    echo 'Start - Build and push image with Jenkins docker-plugin'
                    withDockerServer([uri: "127.0.0.1:4243"]) {
                        withDockerRegistry([credentialsId: 'ECRRegistry', url: "https://932833910912.dkr.ecr.us-east-1.amazonaws.com/petclinicrepo:latest"]) {
                            // we give the image the same version as the .war package
                            def image = docker.build("docker.sample.registry.com/fego-ext", "--build-arg PACKAGE_VERSION=1.1 ./")
                            image.push()
                            echo 'Done pushing the image.'
                        }
                    }
                }
            }
        }
       
    }
}
